# -*- coding: utf-8 -*-
"""CONTACT BOOK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8szBfbE9BkAja19tMsRSDqe4sj-mHtg
"""

contacts = {}

def add_contact(name, phone, email, address):
    contacts[name] = {'phone': phone, 'email': email, 'address': address}
    print(f"Contact '{name}' added successfully.")

def view_contacts():
    if contacts:
        print("Contact List:")
        for name, contact in contacts.items():
            print(f"Name: {name}, Phone: {contact['phone']}")
    else:
        print("Contact list is empty.")

def search_contact(search_term):
    results = []
    for name, contact in contacts.items():
        if search_term in name or search_term in contact['phone']:
            results.append((name, contact))

    if results:
        print("Search Results:")
        for name, contact in results:
            print(f"Name: {name}, Phone: {contact['phone']}")
    else:
        print("No matching contacts found.")

def update_contact(name, phone, email, address):
    if name in contacts:
        contacts[name] = {'phone': phone, 'email': email, 'address': address}
        print(f"Contact '{name}' updated successfully.")
    else:
        print(f"Contact '{name}' not found.")

def delete_contact(name):
    if name in contacts:
        del contacts[name]
        print(f"Contact '{name}' deleted successfully.")
    else:
        print(f"Contact '{name}' not found.")

def display_menu():
    print("\nContact Management System")
    print("1. Add Contact")
    print("2. View Contact List")
    print("3. Search Contact")
    print("4. Update Contact")
    print("5. Delete Contact")
    print("6. Exit")

def main():
    while True:
        display_menu()
        choice = input("Enter your choice: ")

        if choice == '1':
            name = input("Enter name: ")
            phone = input("Enter phone number: ")
            email = input("Enter email: ")
            address = input("Enter address: ")
            add_contact(name, phone, email, address)
        elif choice == '2':
            view_contacts()
        elif choice == '3':
            search_term = input("Enter name or phone number to search: ")
            search_contact(search_term)
        elif choice == '4':
            name = input("Enter name of contact to update: ")
            phone = input("Enter updated phone number: ")
            email = input("Enter updated email: ")
            address = input("Enter updated address: ")
            update_contact(name, phone, email, address)
        elif choice == '5':
            name = input("Enter name of contact to delete: ")
            delete_contact(name)
        elif choice == '6':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

if __name__ == "__main__":
    main()