# -*- coding: utf-8 -*-
"""PASSWORD GENERATOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFlU5uHoShhQ8vTfZ9_rETdzCJnAFPpl
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    length = int(input("Enter the desired length of the password: "))

    if length > 0:
        password = generate_password(length)
        print(f"Generated password: {password}")
    else:
        print("Please enter a valid length for the password (greater than 0).")

if __name__ == "__main__":
    main()